# Generated by Django 4.2.2 on 2023-06-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
