# Generated by Django 4.2.2 on 2023-06-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_wishitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
