# Generated by Django 4.2.2 on 2023-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
